### ISSUE TITLE
[Documentation] Render project links in PyPI page

### ISSUE THREAD

**Issue by tai271828** [solvcon/shocktube1dcalc#1]
## Type
* [ ] Content inaccurate
* [x] Content missing
* [ ] Typo

## URL

https://pypi.org/project/shocktube1dcalc/

## Description

We may want the following links in the PyPI page
- homepage (github project)
- issue tracker
- code
- documentation

**Comment by tai271828** [comment]
By tweaking pyproject managed by poetry we could complete this task https://python-poetry.org/docs/pyproject/

**Comment by yungyuc** [comment]
Will the document be generated in a typeset form?  Maybe by CI or something else?

**Comment by tai271828** [comment]
> Will the document be generated in a typeset form? Maybe by CI or something else?

I did not follow what you meant by "typeset form". Poetry will generate meta-data for the package. I am not sure which format poetry generated, and we could have a look later on.

**Comment by yungyuc** [comment]
Oh sorry I misunderstood what you meant for the `[Documentation]` tag in the subject line.  You are updating the information that will go to PyPI.

What I meant for typesetting is something like https://yyc.solvcon.net/en/latest/writing/2015/euler.html to be generated somewhere.  I think a solver of a specific problem needs pages to document the equations and visualization of the results and they should be typeset.  Do you have a plan for doing that?

**Comment by tai271828** [comment]
I don't have such plan. However, it sounds a good idea to me!

Maybe correlates this old slack thread :)  https://solvcon.slack.com/archives/C030M15GZ/p1553560440024400
