### ISSUE TITLE
[Documentation] Solvcon shocktube document url can’t arrive

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/shocktube1dcalc#4]
## Type
* [ ] Content inaccurate
* [x] Content missing
* [ ] Typo

## URL

`shocktube1dcalc/cese.py `
`shocktube1dcalc/solver_analytic.py `

## Description

The cese & shocktube reference url in docstring can’t arrive.

**Comment by tai271828** [comment]
Thank you for reporting the issue. I will have a look.

**Comment by tai271828** [comment]
The page of the url pointing to is outdated, so let me just remove it.
